development:
  project_id: tpac-8c41e
  database_url: https://tpac-8c41e-default-rtdb.firebaseio.com/

test:
  project_id: tpac-8c41e
  database_url: https://tpac-8c41e-default-rtdb.firebaseio.com/

production:
  project_id: tpac-8c41e
  database_url: https://tpac-8c41e-default-rtdb.firebaseio.com/